In [6]:
import pandas as pd
train_dataset = pd.read_csv("D:\\File\\train_dataset\\train_set.csv")

In [7]:
train_dataset.head(5)

,Title,Abstract,Keywords,Label
0,Genetics of migraine: where are we now?,Migraine is a complex brain disorder explained...,Familial hemiplegic migraine; Genetics; Genome...,832
1,The protective gene dose effect of the APOE 2 ...,Introduction: Harboring two copies of the apol...,Alzheimer s disease; Alzheimer s disease signa...,46
2,Improved detection of sentinel lymph node meta...,An improved procedure that allows accurate det...,Frozen section; Metastases; Sentinel lymph nod...,348
3,Adherence and persistence among patients with ...,"Aim: To compare 6 month adherence, persistence...",GLP 1; dulaglutide; exenatide; type 2 diabetes.,450
4,"The shaping ability of Wave One Gold, TRUShape...",Aim: To compare the shaping ability of a heat ...,endodontic files; microcomputed tomography; ov...,675

In [4]:
train_dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 842424 entries, 0 to 842423
Data columns (total 4 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   Title     842424 non-null  str
 1   Abstract  842424 non-null  str
 2   Keywords  635583 non-null  str
 3   Label     842424 non-null  int64
dtypes: int64(1), str(3)
memory usage: 25.7 MB

In [9]:
train_dataset.duplicated().sum()

np.int64(154)

In [12]:
# Basic EDA for train_dataset
print(f"Shape: {train_dataset.shape}")
print(f"Columns: {list(train_dataset.columns)}")

dup_all = train_dataset.duplicated().sum()
print(f"\nDuplicate rows (all columns): {dup_all} ({dup_all / len(train_dataset):.2%})")

lower_to_actual = {c.lower(): c for c in train_dataset.columns}

# Try to detect a text column for duplicate text checks.
text_candidates = ["text", "sentence", "content", "review", "comment", "tweet", "post", "question", "title"]
text_col = next((lower_to_actual[c] for c in text_candidates if c in lower_to_actual), None)

if text_col is None:
    object_cols = train_dataset.select_dtypes(include=["object", "string"]).columns.tolist()
    text_col = object_cols[0] if object_cols else None

if text_col:
    dup_text = train_dataset[text_col].duplicated().sum()
    print(f"Duplicate values in '{text_col}': {dup_text} ({dup_text / len(train_dataset):.2%})")

# Try to detect the label column.
label_candidates = ["label", "labels", "target", "class", "category", "intent", "y"]
label_col = next((lower_to_actual[c] for c in label_candidates if c in lower_to_actual), None)

if label_col is None:
    nunique = train_dataset.nunique(dropna=False).sort_values()
    possible_labels = [c for c in nunique.index if 1 < nunique[c] <= 50]
    label_col = possible_labels[0] if possible_labels else None

if label_col:
    distinct_labels = train_dataset[label_col].nunique(dropna=False)
    print(f"\nDetected label column: '{label_col}'")
    print(f"Number of distinct labels: {distinct_labels}")
    print("Label distribution:")
    print(train_dataset[label_col].value_counts(dropna=False))
else:
    print("\nCould not auto-detect a label column. Please set label_col manually.")

print("\nMissing values by column:")
print(train_dataset.isna().sum().sort_values(ascending=False))

Shape: (842424, 4)
Columns: ['Title', 'Abstract', 'Keywords', 'Label']

Duplicate rows (all columns): 154 (0.02%)
Duplicate values in 'Title': 3871 (0.46%)

Detected label column: 'Label'
Number of distinct labels: 1406
Label distribution:
Label
5       6544
564     6518
683     6422
268     6122
814     5964
        ...
1288      68
620       65
1237      65
105       64
241       62
Name: count, Length: 1406, dtype: int64

Missing values by column:
Keywords    206841
Title            0
Abstract         0
Label            0
dtype: int64

In [1]:
import pandas as pd
journal_dataset = pd.read_csv("D:\\File\\train_dataset\\journal_category.csv")

In [2]:
journal_dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 1406 entries, 0 to 1405
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Journal     1406 non-null   str
 1   Aims        1406 non-null   str
 2   Label       1406 non-null   int64
 3   Categories  1406 non-null   str
dtypes: int64(1), str(3)
memory usage: 44.1 KB

In [3]:
journal_dataset.head()

,Journal,Aims,Label,Categories
0,Therapeutic Advances in Neurological Disorders,Therapeutic Advances in Neurological Disorders...,1340,"Neurology (clinical), Neurology, Pharmacology"
1,International Journal of Infectious Diseases,The International Journal of Infectious Diseas...,694,"Infectious Diseases, Medicine (miscellaneous),..."
2,Acta Physiologica,Acta Physiologica is an important forum for th...,22,Physiology
3,Psychology and Aging,Psychology and Aging publishes original artic...,1224,"Aging, Geriatrics and Gerontology, Social Psyc..."
4,Endocrinology and Metabolism Clinics of North ...,Endocrinology and Metabolism Clinics of North ...,484,"Endocrinology, Endocrinology, Diabetes and Met..."

In [4]:
import pandas as pd
journal_full_dataset = pd.read_csv("D:\\File\\train_dataset\\journal_full_info.csv")

In [5]:
journal_full_dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 1406 entries, 0 to 1405
Data columns (total 22 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   Journal                                       1406 non-null   str
 1   Aims                                          1406 non-null   str
 2   Label                                         1406 non-null   int64
 3   Rank by SJR                                   1406 non-null   int64
 4   Best Rank                                     1406 non-null   int64
 5   Title_modified                                1406 non-null   str
 6   URL                                           1406 non-null   str
 7   URL_Scimago                                   1406 non-null   str
 8   SJR index                                     1406 non-null   str
 9   Best Quartile                                 1406 non-null   str
 10  H index                                       1406 non-null   int64
 11  Scope                                         1406 non-null   str
 12  Best Categories                               1406 non-null   str
 13  Biochemistry, Genetics and Molecular Biology  1406 non-null   int64
 14  Medicine                                      1406 non-null   int64
 15  Immunology and Microbiology                   1406 non-null   int64
 16  Pharmacology, Toxicology and Pharmaceutics    1406 non-null   int64
 17  Neuroscience                                  1406 non-null   int64
 18  Health Professions                            1406 non-null   int64
 19  Nursing                                       1406 non-null   int64
 20  Psychology                                    1406 non-null   int64
 21  Dentistry                                     1406 non-null   int64
dtypes: int64(13), str(9)
memory usage: 241.8 KB